# Create a folder under the drive root
$ mkdir actions-runner; cd actions-runner# Download the latest runner package
$ Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-win-x64-2.312.0.zip -OutFile actions-runner-win-x64-2.312.0.zip#
$ if((Get-FileHash -Path actions-runner-win-x64-2.312.0.zip -Algorithm SHA256).Hash.ToUpper() -ne '847dbba12e7d0ae8f280481cf270110892a94657b63a6a4ab2da41c2b9831191'.ToUpper()){ throw 'Computed checksum did not match' }# Extract the installer
$ Add-Type -AssemblyName System.IO.Compression.FileSystem ; [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.312.0.zip", "$PWD")
# Create the runner and start the configuration experience
$ ./config.cmd --url https://github.com/Freddyrogue/test --token AHXFEJP5WAR6IDKJCSYSRIDFYCPXA# Run it!
$ ./run.cmd
# Use this YAML in your workflow file for each job
runs-on: self-hosted
